language: node_js

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '14'

git:
  depth: 3

script:
  - yarn test

notifications:
  email:
    recipients:
      - aduartem@miumg.edu.gt
      - alan@warava.com
  on_success: always
  on_failure: always

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: travis-be-express
  on:
    repo: aduam/travis-BE-express